# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d08234893f5ce3f55f2d49c6eac61b0a8264033265bf6154b6f25af0b171b0e53b7e5f1649feefacef65b520043902988e504a41532d8dea184847a2f58f8559

test:
  secret_key_base: 33cae1ee5b9dd9d1bba30a1a322fc5a2ea1179dff615701ee27701d68e5164cbd2f8514c85c4cd4a48f6bc465f82e2262dc5ec8d8e8e02dc221a9d5b0f111905

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
